kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: audit
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  kubeProxyMode: "nftables"
featureGates:
  KubeletPSI: true
nodes:
- role: control-plane

  # Porta utile per i test HTTP
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: tcp
  image: kindest/node:v1.34.0

  # Configurazioni specifiche per il control plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        # enable auditing flags on the API server
        extraArgs:
          audit-log-path: /var/log/kubernetes/audit.log
          audit-policy-file: /etc/kubernetes/audit-policy.yaml
          tracing-config-file: /etc/kubernetes/tracing.yaml
        # mount new files / directories on the control plane
        extraVolumes:
          - name: audit-policies
            hostPath: /etc/kind/audit-policy.yaml
            mountPath: /etc/kubernetes/audit-policy.yaml
            readOnly: true
            pathType: "File"
          - name: tracing
            hostPath: /etc/kind/tracing.yaml
            mountPath: /etc/kubernetes/tracing.yaml
            readOnly: true
            pathType: "File"
          - name: "audit-logs"
            hostPath: "/var/log/kubernetes"
            mountPath: "/var/log/kubernetes"
            readOnly: false
            pathType: DirectoryOrCreate

  # Mount della policy di audit, journal (per Grafana) e log di Kubernetes
  extraMounts:
  - hostPath: /etc/kind/audit-policy.yaml
    containerPath: /etc/kind/audit-policy.yaml
    readOnly: true
  - hostPath: /etc/kind/tracing.yaml
    containerPath: /etc/kind/tracing.yaml
    readOnly: true
  - hostPath: /var/log/kubernetes/
    containerPath: /var/log/kubernetes/
    readOnly: false
  - hostPath: /var/log/journal/
    containerPath: /var/log/journal/
    readOnly: false
